/*
 * TACTILE_SWITCH_private.h
 *
 *  Created on: Feb 25, 2016
 *      Author: Anwar
 */

#ifndef TACTILE_SWITCH_PRIVATE_H_
#define TACTILE_SWITCH_PRIVATE_H_

/*Comment!: STATES OF FUNCTION */
#define TACTILE_u8SWITCHSTATERELEASED 0
#define TACTILE_u8SWITCHSTATEDEBOUNCING 1
#define TACTILE_u8SWITCHSTATEPRESSED 2


/*Comment!: START OF LOOPING */
#define TACTILE_u8ZEROLOOPINDX 0

/*Comment!: START OF COUNTING */
#define TACTILE_u8COUNTINITVAL 0

/*Comment!:MAX NUMBER OF SWITCHES */
#define TACTILE_MAXSWITCH 16

/*Comment!: MAX COUNT TO SWITCH STATE */
#define MAX_COUNT 50
#endif /* TACTILE_SWITCH_PRIVATE_H_ */
